#
# Since host.docker.internal domain name doesn't work on linux OS
# It is better to use the docker container instead of local installation of PostgreSQL DB.
#
#version: '3.7'
#services:
#  keycloak-authorization-server:
#    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
#    hostname: keycloak-server
#    ports:
#      - "9091:9091"
#    environment:
#      - "KEYCLOAK_USER=admin"
#      - "KEYCLOAK_PASSWORD=admin"
#      - "JAVA_OPTS=-Djboss.http.port=9091"
#      - "DB_VENDOR=POSTGRES"
#      - "DB_ADDR=host.docker.internal"
#      - "DB_DATABASE=keycloak"
#      - "DB_USER=keycloak"
#      - "DB_SCHEMA=keycloak"
#      - "DB_PASSWORD=keycloak"

version: '3.7'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - "POSTGRES_DB=keycloak"
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=keycloak"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    ports:
      - "9091:9091"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "KEYCLOAK_LOGLEVEL=DEBUG"
      - "JAVA_OPTS=-Djboss.http.port=9091"
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=postgres"
      - "DB_DATABASE=keycloak"
      - "DB_USER=keycloak"
      - "DB_SCHEMA=public"
      - "DB_PASSWORD=keycloak"
    depends_on:
      - postgres
